services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=feng
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: fest_orders_api
    environment:
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - db

  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: fest_orders_web
    depends_on:
      - api
