name: CI - Fest Orders

# 1. Quando essa automação vai rodar?
on:
  push:
    branches: [ "master", "main", "dev-v.03" ]

jobs:
  build-and-test:
    # 2. Onde o robô do GitHub vai rodar? Em uma máquina Ubuntu novinha.
    runs-on: ubuntu-latest

    steps:
      # 3. Baixa o seu código do GitHub para a máquina do robô
      - name: Checkout do código
        uses: actions/checkout@v4

      # 4. Usa o Docker Compose para tentar "buildar" as imagens
      - name: Build das imagens Docker
        run: docker compose build
