name: CI/CD - Fest Orders

on:
  push:
    branches: [ "master", "main", "dev-v.03" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # Novo passo: O robô faz login no seu Docker Hub usando o cofre!
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Empacota e envia a API (Back-end)
      - name: Build e Push da API
        run: |
          docker build -t viniyuhs/fest-orders-api:latest ./back
          docker push viniyuhs/fest-orders-api:latest

      # Empacota e envia o Angular (Front-end)
      - name: Build e Push do Front
        run: |
          docker build -t viniyuhs/fest-orders-web:latest ./front
          docker push viniyuhs/fest-orders-web:latest
